=== dianasaz/JavaWebDevelopment/Task3/src/main/resources/medicins.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Medicins" type="MedicinsType"/>
  <xs:complexType name="CertificateType">
    <xs:sequence>
      <xs:element type="xs:date" name="Date"/>
      <xs:element type="xs:string" name="Organization"/>
    </xs:sequence>
    <xs:attribute type="xs:int" name="number" use="optional"/>
  </xs:complexType>
  <xs:complexType name="DosageType">
    <xs:sequence>
      <xs:element type="xs:int" name="Dose"/>
      <xs:element type="xs:int" name="Period"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PackageType">
    <xs:sequence>
      <xs:element type="xs:string" name="TypeOfPackage"/>
      <xs:element type="xs:int" name="Quantity"/>
      <xs:element type="xs:int" name="Price"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="PharmType">
    <xs:sequence>
      <xs:element type="CertificateType" name="Certificate"/>
      <xs:element type="DosageType" name="Dosage"/>
      <xs:element type="PackageType" name="Package"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="nameOfPharm" use="optional"/>
  </xs:complexType>
  <xs:complexType name="VersionType">
    <xs:sequence>
      <xs:element type="PharmType" name="Pharm"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="versionType" use="optional"/>
  </xs:complexType>
  <xs:complexType name="MedicineType">
    <xs:sequence>
      <xs:element type="xs:string" name="Group"/>
      <xs:element name="Analogs">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Analog" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element type="VersionType" name="Version"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
  </xs:complexType>
  <xs:complexType name="MedicinsType">
    <xs:sequence>
      <xs:element type="MedicineType" name="Medicine" maxOccurs="unbounded" minOccurs="16"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== dianasaz/JavaWebDevelopment/Task3/src/main/resources/medicins.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Medicins  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="medicins.xsd">
    <Medicine name = "Gripex">
        <Group>ANTIBIOTICS</Group>
        <Analogs>
            <Analog>TeraFlu</Analog>
            <Analog>AntiGrippin</Analog>
        </Analogs>
        <Version versionType = "TABLETS">
            <Pharm nameOfPharm = "PolMed">
                <Certificate number = "1348765">
                    <Date>2019-07-09</Date>
                    <Organization>Opera</Organization>
                </Certificate>
                <Dosage>
                    <Dose>1</Dose>
                    <Period>2</Period>
                </Dosage>
                <Package>
                    <TypeOfPackage>HARD</TypeOfPackage>
                    <Quantity>20</Quantity>
                    <Price>230</Price>
                </Package>
            </Pharm>
        </Version>
    </Medicine>
    <Medicine name = "TeraFlu">
        <Group>ANTIBIOTICS</Group>
        <Analogs>
            <Analog>AntiGrippin</Analog>
        </Analogs>
        <Version versionType = "POWDER">
            <Pharm nameOfPharm = "PolMed">
                <Certificate number = "1348765">
                    <Date>2018-06-13</Date>
                    <Organization>FireFox</Organization>
                </Certificate>
                <Dosage>
                    <Dose>1</Dose>
                    <Period>2</Period>
                </Dosage>
                <Package>
                    <TypeOfPackage>SEMIHARD</TypeOfPackage>
                    <Quantity>20</Quantity>
                    <Price>290</Price>
                </Package>
            </Pharm>
        </Version>
    </Medicine>
    <Medicine name = "AntiKashel'">
        <Group>ANTIBIOTICS</Group>
        <Analogs>
            <Analog>Grippex</Analog>
            <Analog>AntiGrippin</Analog>
        </Analogs>
        <Version versionType = "POWDER">
            <Pharm nameOfPharm = "PolMed">
                <Certificate number = "12228765">
                    <Date>2017-09-14</Date>
                    <Organization>Opera</Organization>
                </Certificate>
                <Dosage>
                    <Dose>2</Dose>
                    <Period>1</Period>
                </Dosage>
                <Package>
                    <TypeOfPackage>HARD</TypeOfPackage>
                    <Quantity>30</Quantity>
                    <Price>250</Price>
                </Package>
            </Pharm>
        </Version>
    </Medicine>
    <Medicine name = "Iod">
        <Group>ANTIALLERGIAN</Group>
        <Analogs>
            <Analog>Suprastin</Analog>
        </Analogs>
        <Version versionType = "DRAGEE">
            <Pharm nameOfPharm = "BelMed">
                <Certificate number = "80008765">
                    <Date>2019-12-28</Date>
                    <Organization>Mazila</Organization>
                </Certificate>
                <Dosage>
                    <Dose>1</Dose>
                    <Period>1</Period>
                </Dosage>
                <Package>
                    <TypeOfPackage>SOFT</TypeOfPackage>
                    <Quantity>10</Quantity>
                    <Price>90</Price>
                </Package>
            </Pharm>
        </Version>
    </Medicine>
    <Medicine name = "ShortNose">
        <Group>PAINKILLERS</Group>
        <Analogs>
        </Analogs>
        <Version versionType = "CAPSULE">
            <Pharm nameOfPharm = "BelMed">
                <Certificate number = "12298215">
                    <Date>2014-11-06</Date>
                    <Organization>Opera</Organization>
                </Certificate>
                <Dosage>
                    <Dose>5</Dose>
                    <Period>3</Period>
                </Dosage>
                <Package>
                    <TypeOfPackage>SEMIHARD</TypeOfPackage>
                    <Quantity>32</Quantity>
                    <Price>270</Price>
                </Package>
            </Pharm>
        </Version>
    </Medicine>
</Medicins>
